const productActions = {
  SIMPLE_ACTION: 'SIMPLE_ACTION',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
};

const overviewActions = {
  SET_OVERVIEW: 'SET_OVERVIEW',
  SET_SUMMARY: 'SET_SUMMARY',
  SET_SUBSCRIBED_INGREDIENTS: 'SET_SUBSCRIBED_INGREDIENTS',
  SET_WATCHED_INGREDIENTS: 'SET_WATCHED_INGREDIENTS',
  SET_ACTIVE_PRODUCTS: 'SET_ACTIVE_PRODUCTS',
  SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
  SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT',
  CHANGE_VERSION: 'CHANGE_VERSION',
  SET_CONCEPT_PRODUCTS: 'SET_CONCEPT_PRODUCTS'
};

const adminActions = {
  SET_REPORT: 'SET_REPORT',
  ADD_NEW_REPORT: 'ADD_NEW_REPORT',
  SELECT_REPORT: 'SELECT_REPORT',
  UPDATE_REPORT: 'UPDATE_REPORT',
  SET_USERS: 'SET_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_LOGGEDIN_USER_REPORT: 'SET_LOGGEDIN_USER_REPORT',
  ADD_LOGGEDIN_USER_NEW_REPORT: 'ADD_LOGGEDIN_USER_NEW_REPORT'
};

const authActions = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  SET_TOKEN: 'SET_TOKEN',
  CLEAR_STATE: 'CLEAR_STATE',
  SET_ROLE: 'SET_ROLE'
};

const dashboardActions = {
  SET_SEARCH_RESULT: 'SET_SEARCH_RESULT'
};

export const Actions = {
  productActions,
  overviewActions,
  adminActions,
  authActions,
  dashboardActions
};
